/*----- HERE WE CREATE OUR SCHEMA BASED ON THE CONSEPTIONAL DESIGN AND WE SEED THE TABLES FOR TESTING PURPOSE -----*/

/* NOTES
	- ALL TABLES PRIMARY KEYS ARE ALSO IDENTITY COLUMN SO IT CREATES ID NUMBERS AS DATA INSERTED
	- STRING DATA TYPES ASSIGN AS ANSI STANDARD OFF FOR LOWER METADATA. IT CAN BE CHANGE LATER IF NEEDED
	
*/


/*----1)___CREATING TABLES
---------------------------------------------------------------
 - User TABLE ---------- IN THIS TABLE LIBRARY USERS WILL BE STORED WITH THEIR FULL NAME AND CONTACT INFORMATION
*/


CREATE TABLE [User] (
	UserID			INT				PRIMARY KEY		IDENTITY(1,1),			
	FirstName		VARCHAR(50)		NOT NULL,								
	LastName		VARCHAR(50)		NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PhoneNumber		VARCHAR(10)		NOT NULL,								
	[Address]		VARCHAR(100)	NOT NULL
);
GO


-- RefAuthor TABLE ------- ALL AUTHORS WILL BE STORED IN THIS TABLE

CREATE TABLE [RefAuthor] (
	AuthorID		INT				PRIMARY KEY		IDENTITY(1,1),
	AuthorName		VARCHAR(100)	NOT NULL
);
GO

-- RefBookTitle TABLE----- ALL UNIQUE BOOK TITLES WILL BE STORED IN THIS TABLE

CREATE TABLE [RefBookTitle] (
	BookTitleID			INT				PRIMARY KEY		IDENTITY,
	BookTitle			VARCHAR(200)	NOT NULL,
	ISBN				BIGINT			NOT NULL,
	AuthorID			INT				NOT NULL,
	CONSTRAINT FK_RefBookTitle_AuthorID FOREIGN KEY (AuthorID) REFERENCES [RefAuthor](AuthorID)
);
GO

 
-- Book TABLE------------- ALL PHYSICAL COPIES WILL BE STORED IN THIS TABLE

CREATE TABLE [Book] (
	BookID				INT PRIMARY KEY IDENTITY,
	BookTitleID			INT NOT NULL,
	CONSTRAINT FK_Book_BookTitleID FOREIGN KEY (BookTitleID) REFERENCES [RefBookTitle](BookTitleID)
);
GO


--UserBookLoan TABLE--------- TABLE FOR CHECKOUT 

CREATE TABLE UserBookLoan (
	LoanID				INT IDENTITY,
	UserID				INT NOT NULL,
	BookID				INT NOT NULL,
	CheckOutDate		DATE NOT NULL,
	DueDate				DATE NOT NULL,
	ReturnedDate		DATE,
	CONSTRAINT FK_User_UserID FOREIGN KEY (UserID) REFERENCES [User](UserID),
	CONSTRAINT FK_Book_BookID FOREIGN KEY (BookID) REFERENCES Book(BookID)
);
GO

